# 配置文件使用 [[tasks]] 结构
[[tasks]]
name = "movie"
target_root = "/home/ling/media/movies"
link_mode = "hardlink"
source = "/mnt/storage/raw_movies"
patterns = ["**/*.mkv"]
ignore_patterns = ["**/EXTRAS/**", "**/Sample/**"]

[[tasks]]
name = "anime"
target_root = "/home/ling/media/anime"
link_mode = "symlink"
source = "/mnt/storage/raw_anime"
patterns = ["**/*.mkv", "**/*.mp4"]
